export const FORUM_CREATE_BOARD_REQUESTED = "FORUM_CREATE_BOARD_REQUESTED";
export const FORUM_CREATE_BOARD_SUCCEEDED = "FORUM_CREATE_BOARD_SUCCEEDED";
export const FORUM_CREATE_BOARD_FAILED = "FORUM_CREATE_BOARD_FAILED";

export const FORUM_GET_BOARD_REQUESTED = "FORUM_GET_BOARD_REQUESTED";
export const FORUM_GET_BOARD_SUCCEEDED = "FORUM_GET_BOARD_SUCCEEDED";
export const FORUM_GET_BOARD_FAILED = "FORUM_GET_BOARD_FAILED";

export const FORUM_GET_BOARDS_REQUESTED = "FORUM_GET_BOARDS_REQUESTED";
export const FORUM_GET_BOARDS_SUCCEEDED = "FORUM_GET_BOARDS_SUCCEEDED";
export const FORUM_GET_BOARDS_FAILED = "FORUM_GET_BOARDS_FAILED";

export const FORUM_EDIT_BOARD_REQUESTED = "FORUM_EDIT_BOARD_REQUESTED";
export const FORUM_EDIT_BOARD_SUCCEEDED = "FORUM_EDIT_BOARD_SUCCEEDED";
export const FORUM_EDIT_BOARD_FAILED = "FORUM_EDIT_BOARD_FAILED";

export const FORUM_DELETE_BOARD_REQUESTED = "FORUM_DELETE_BOARD_REQUESTED";
export const FORUM_DELETE_BOARD_SUCCEEDED = "FORUM_DELETE_BOARD_SUCCEEDED";
export const FORUM_DELETE_BOARD_FAILED = "FORUM_DELETE_BOARD_FAILED";

export const FORUM_CREATE_THREAD_REQUESTED = "FORUM_CREATE_THREAD_REQUESTED";
export const FORUM_CREATE_THREAD_SUCCEEDED = "FORUM_CREATE_THREAD_SUCCEEDED";
export const FORUM_CREATE_THREAD_FAILED = "FORUM_CREATE_THREAD_FAILED";

export const FORUM_GET_THREAD_REQUESTED = "FORUM_GET_THREAD_REQUESTED";
export const FORUM_GET_THREAD_SUCCEEDED = "FORUM_GET_THREAD_SUCCEEDED";
export const FORUM_GET_THREAD_FAILED = "FORUM_GET_THREAD_FAILED";

export const FORUM_GET_THREADS_REQUESTED = "FORUM_GET_THREADS_REQUESTED";
export const FORUM_GET_THREADS_SUCCEEDED = "FORUM_GET_THREADS_SUCCEEDED";
export const FORUM_GET_THREADS_FAILED = "FORUM_GET_THREADS_FAILED";

export const FORUM_EDIT_THREAD_REQUESTED = "FORUM_EDIT_THREAD_REQUESTED";
export const FORUM_EDIT_THREAD_SUCCEEDED = "FORUM_EDIT_THREAD_SUCCEEDED";
export const FORUM_EDIT_THREAD_FAILED = "FORUM_EDIT_THREAD_FAILED";

export const FORUM_DELETE_THREAD_REQUESTED = "FORUM_DELETE_THREAD_REQUESTED";
export const FORUM_DELETE_THREAD_SUCCEEDED = "FORUM_DELETE_THREAD_SUCCEEDED";
export const FORUM_DELETE_THREAD_FAILED = "FORUM_DELETE_THREAD_FAILED";
