/*
 * Registration
 */
export const USER_CREATE_REQUESTED = "USER_CREATE_REQUESTED";
export const USER_CREATE_SUCCEEDED = "USER_CREATE_SUCCEEDED";
export const USER_CREATE_FAILED = "USER_CREATE_FAILED";

/*
 * Login
 */
export const USER_AUTH_REQUESTED = "USER_AUTH_REQUESTED";
export const USER_AUTH_SUCCEEDED = "USER_AUTH_SUCCEEDED";
export const USER_AUTH_FAILED = "USER_AUTH_FAILED";

/*
 * Logout
 */
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";
export const USER_LOGOUT_SUCCEEDED = "USER_LOGOUT_SUCCEEDED";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

/*
 * Change password
 */
export const USER_CHANGE_PASSWD_REQUESTED = "USER_CHANGE_PASSWD_REQUESTED";
export const USER_CHANGE_PASSWD_SUCCEEDED = "USER_CHANGE_PASSWD_SUCCEEDED";
export const USER_CHANGE_PASSWD_FAILED = "USER_CHANGE_PASSWD_FAILED";
